# Site settings
title: Midwives in Vancouver
#email: your-email@domain.com
description: "Professionally trained and registered midwives in Vancouver BC"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://midwivesinvancouver.ca" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

#Specific step for nitrous because it serves on a different root IP
host: 0.0.0.0
